version: '2'
services:
  pradera-app:
    image: pradera
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pradera-postgresql:5432/pradera
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://pradera-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://pradera-elasticsearch:9200
    ports:
      - 8080:8080
  pradera-postgresql:
    extends:
      file: postgresql.yml
      service: pradera-postgresql
  pradera-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: pradera-elasticsearch
